In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df = pd.read_csv("data/2025-01-01_istdaten.csv", sep=";")

/tmp/ipykernel_286060/947969522.py:1: DtypeWarning: Columns (0: LINIEN_ID, 1: LINIEN_TEXT, 2: UMLAUF_ID) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/2025-01-01_istdaten.csv", sep=";")

In [4]:
test_df = df[df["BETREIBER_NAME"].str.contains("MBC") & df["LINIEN_TEXT"].str.contains("705")]
test_df.head(10)

,BETRIEBSTAG,FAHRT_BEZEICHNER,BETREIBER_ID,BETREIBER_ABK,BETREIBER_NAME,PRODUKT_ID,LINIEN_ID,LINIEN_TEXT,UMLAUF_ID,VERKEHRSMITTEL_TEXT,...,FAELLT_AUS_TF,BPUIC,HALTESTELLEN_NAME,ANKUNFTSZEIT,AN_PROGNOSE,AN_PROGNOSE_STATUS,ABFAHRTSZEIT,AB_PROGNOSE,AB_PROGNOSE_STATUS,DURCHFAHRT_TF
419834,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8579234,"Ecublens VD, EPFL Piccard",NaN,NaN,NaN,01.01.2025 06:30,01.01.2025 06:30:42,REAL,False
419835,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8579233,"Ecublens VD, EPFL (bus)",01.01.2025 06:30,01.01.2025 06:31:22,REAL,01.01.2025 06:30,01.01.2025 06:32:13,REAL,False
419836,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8591952,"Ecublens VD, Ormet",01.01.2025 06:33,01.01.2025 06:33:57,REAL,01.01.2025 06:33,01.01.2025 06:34:02,REAL,False
419837,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8591949,"Ecublens VD, En Enjalin",01.01.2025 06:34,01.01.2025 06:34:43,REAL,01.01.2025 06:34,01.01.2025 06:34:48,REAL,False
419838,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8591954,"Ecublens VD, Perrettes",01.01.2025 06:34,01.01.2025 06:35:15,REAL,01.01.2025 06:34,01.01.2025 06:35:20,REAL,False
419839,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8591961,"Ecublens VD, Villars",01.01.2025 06:35,01.01.2025 06:36:05,REAL,01.01.2025 06:35,01.01.2025 06:36:10,REAL,False
419840,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8592248,"Ecublens VD, Larges-Pièces",01.01.2025 06:37,01.01.2025 06:37:48,REAL,01.01.2025 06:37,01.01.2025 06:37:53,REAL,False
419841,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8592244,"Echandens, Chocolatière",01.01.2025 06:40,01.01.2025 06:40:18,REAL,01.01.2025 06:40,01.01.2025 06:40:23,REAL,False
419842,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8592243,"Echandens, Riaz",01.01.2025 06:41,01.01.2025 06:41:21,REAL,01.01.2025 06:41,01.01.2025 06:41:26,REAL,False
419843,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,False,8588875,"Echandens, centre",01.01.2025 06:42,01.01.2025 06:42:01,REAL,01.01.2025 06:42,01.01.2025 06:42:06,REAL,False

In [16]:
test_df["DELAY"] = abs(pd.to_datetime(test_df["AB_PROGNOSE"]) - pd.to_datetime(test_df["ABFAHRTSZEIT"]))
test_df.head(10)

,BETRIEBSTAG,FAHRT_BEZEICHNER,BETREIBER_ID,BETREIBER_ABK,BETREIBER_NAME,PRODUKT_ID,LINIEN_ID,LINIEN_TEXT,UMLAUF_ID,VERKEHRSMITTEL_TEXT,...,HALTESTELLEN_NAME,ANKUNFTSZEIT,AN_PROGNOSE,AN_PROGNOSE_STATUS,ABFAHRTSZEIT,AB_PROGNOSE,AB_PROGNOSE_STATUS,DURCHFAHRT_TF,DELAY,IS_DELAYED
419834,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Ecublens VD, EPFL Piccard",NaN,NaN,NaN,01.01.2025 06:30,01.01.2025 06:30:42,REAL,False,0 days 00:00:42,False
419835,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Ecublens VD, EPFL (bus)",01.01.2025 06:30,01.01.2025 06:31:22,REAL,01.01.2025 06:30,01.01.2025 06:32:13,REAL,False,0 days 00:02:13,False
419836,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Ecublens VD, Ormet",01.01.2025 06:33,01.01.2025 06:33:57,REAL,01.01.2025 06:33,01.01.2025 06:34:02,REAL,False,0 days 00:01:02,False
419837,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Ecublens VD, En Enjalin",01.01.2025 06:34,01.01.2025 06:34:43,REAL,01.01.2025 06:34,01.01.2025 06:34:48,REAL,False,0 days 00:00:48,False
419838,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Ecublens VD, Perrettes",01.01.2025 06:34,01.01.2025 06:35:15,REAL,01.01.2025 06:34,01.01.2025 06:35:20,REAL,False,0 days 00:01:20,False
419839,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Ecublens VD, Villars",01.01.2025 06:35,01.01.2025 06:36:05,REAL,01.01.2025 06:35,01.01.2025 06:36:10,REAL,False,0 days 00:01:10,False
419840,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Ecublens VD, Larges-Pièces",01.01.2025 06:37,01.01.2025 06:37:48,REAL,01.01.2025 06:37,01.01.2025 06:37:53,REAL,False,0 days 00:00:53,False
419841,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Echandens, Chocolatière",01.01.2025 06:40,01.01.2025 06:40:18,REAL,01.01.2025 06:40,01.01.2025 06:40:23,REAL,False,0 days 00:00:23,False
419842,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Echandens, Riaz",01.01.2025 06:41,01.01.2025 06:41:21,REAL,01.01.2025 06:41,01.01.2025 06:41:26,REAL,False,0 days 00:00:26,False
419843,01.01.2025,85:764:5000_705-R-201_0630_B7SN,85:764,MBC Auto,Automobiles MBC,Bus,85:764:705,705,NaN,B,...,"Echandens, centre",01.01.2025 06:42,01.01.2025 06:42:01,REAL,01.01.2025 06:42,01.01.2025 06:42:06,REAL,False,0 days 00:00:06,False

In [26]:
MAX_DELAY_TRESHOLD = pd.Timedelta(minutes=1.5)
test_df["IS_DELAYED"] = False
test_df.loc[pd.to_timedelta(test_df["DELAY"]) >= MAX_DELAY_TRESHOLD, "IS_DELAYED"] = True
print(f"705 is late {len(test_df["IS_DELAYED"] == True) / len(test_df)}% of time")
print(test_df["IS_DELAYED"] == True)

705 is late 1.0% of time
419834    False
419835     True
419836    False
419837    False
419838    False
          ...
421179    False
421180    False
421181    False
421182    False
421183    False
Name: IS_DELAYED, Length: 1350, dtype: bool